### ISSUE TITLE
paper-progress mutates its value (should be read-only)

### ISSUE THREAD

**Issue by jmesserly** [Polymer/paper-progress#11]
Here's an example: http://jsbin.com/huqesocuzu/1/edit?html,console,output

You'll see "oops" in the console. Likewise if you comment out the setter, you get:

```
Exception caught during observer callback: TypeError: Cannot set property value of #<x-foo> which has only a getter
```

You can make it work by having the setter be a no-op.

I think this happens because paper-progress extends core-range. core-range's value property is a bit different, since it's designed to be mutated, whereas I would expect something like paper-progress to only read from its model value. Maybe it should contain a core-range internally for clamping the value, instead of extending from it? Or core-range could use a different property for its input vs output?

**Comment by kevincox** [comment]
For anyone running into this issue I have found a work around to make the data binding unidirectional.  Basically some polymer expressions break the dependency chain and you can use those to prevent the writes back.  It's not super elegant but it is better then creating fake setters that ignore the value (my previous solution).

If your value is a number you can use `{{+myval}}` to break the chain, other wise you can use `{{myVal || myVal}}`.  Of course you don't need to repeat the expression if it is never falsey, or if you can provide a good default `{{myVal || 0}}`.

Hope this helps someone.
